# Generated by Django 6.0.6 on 2026-06-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='divida',
            name='paga',
        ),
        migrations.AddField(
            model_name='divida',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Paga')], default='pendente', max_length=20),
        ),
    ]
